const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const wishlistSchema = new Schema(
  {
    _id: { type: String, required: true }, // userId generated by backend
    items: [{ type: String }], // productIds generated by backend
  },
  { _id: false, timestamps: true },
);

module.exports = mongoose.model("wishlistModel", wishlistSchema, "wishlist");
